### ISSUE TITLE
export class Wallet 

### ISSUE THREAD

**Issue by amethystens** [coinbase/coinbase-sdk-nodejs#100]
mkdir staking-demo
cd staking-demo

**Comment by amethystens** [comment]
> mkdir staking-demo
> cd staking-demo

**Comment by melissamforbs** [comment]
✌️

**Comment by alex-stone** [comment]
Closing this because there is no specific question or bug report! If you have a specific question or a bug report feel free to reach out again here or in our Discord!

Also [here is a Quickstart on our Docs site](https://docs.cdp.coinbase.com/mpc-wallet/docs/quickstart)
