### ISSUE TITLE
A wallet hydration problem

### ISSUE THREAD

**Issue by shleodai** [coinbase/coinbase-sdk-nodejs#144]
Wallet.addresses is empty, when I import a wallet from seed. 
Example
```js
const coinbase = Coinbase.configureFromJson({ filePath: './cdp_api_key.json' });
const user = await coinbase.getDefaultUser();
let wallet = await user.importWallet(seedData);
console.log(wallet.addresses);
```
> [];

This makes `wallet.getDefaultAddress()` return `undefined` every time. 
This could be a bug in the SDK. And it made `wallet.faucet()` unusable. 
However, `wallet.model.default_address` works fine. So, a lot of functionalities remain available. 
Also, after `user.createWallet()`, `wallet.getDefaultAddress()` works fine. The problem only occurs after hydration. Weird.

**Comment by John-peterson-coinbase** [comment]
The `v0.0.15` release (https://github.com/coinbase/coinbase-sdk-nodejs/releases/tag/v0.0.15) resolves this! 

Thank you for raising this issue! cc: @shleodai

**Comment by shleodai** [comment]
Thank you for addressing the issue so quickly! I appreciate the update. The v0.0.15 release makes everything so far working as expected. Thanks again for the prompt resolution!
